### PR TITLE
Structure change

### PR DESCRIPTION
**Pull request by Brandon-Muller**
changed Private Key variable from private_key to privateKey

### CODE REVIEW

**Comment by darylturner** [comment]
Thanks. So guessing they changed the JSON in the API response? Changed job and don’t have a vault setup to test this.

**Comment by Brandon-Muller** [comment]
Appears so! This is my first experience with the app.  Thanks for the initial build, it's a huge help for the Windows guys!

**Comment by darylturner** [comment]
Did you have an issue with it previously? The documentation still says private_key.

https://www.vaultproject.io/api/secret/pki/index.html#generate-certificate

**Comment by Brandon-Muller** [comment]
Interesting. We aren't making requests directly through the CLI, instead allowing users to create a certificate via the web interface. There is a button, after certificate creation, to "Copy credentials."  Which copies JSON code to the clipboard.  This JSON lacks the:  "data": { } portion of the code.  (example below) And, the variable for the private key is:  privateKey  (the value I updated).  

Strange that a direct request would output different variables...  

Also, I was curious, is the getvaultcert.exe that is used in the ReadMe example something additional that you created or obtained from elsewhere? As it doesn't seem to get built with this project. We are currently pasting the copied JSON code, editing in the "data": code in and then piping the file into the executable with powershell.

image

**Comment by darylturner** [comment]
It was something I wrote but I must have missed uploading it to a repository. I believe it was just a thin wrapper for retrieving generated certificate responses from the cubby hole backend.

https://www.vaultproject.io/docs/secrets/cubbyhole/index.html

**Comment by darylturner** [comment]
Unless we wanted to add a CLI flag to support both structures it may be easier to keep what works for you in your own fork. I mean that in nicest way and appreciate the PR.

**Comment by Brandon-Muller** [comment]
I'm totally good with that.  :)  Thanks for looking into it!

**Comment by darylturner** [comment]
If you wanted I could help change the unmarshalling code to support your copy/paste directly? It should just be a 2 or 3 line change to remove the reference to the top level “data” part.

**Comment by Brandon-Muller** [comment]
That would be huge help!

**Comment by darylturner** [comment]
I don't think I can fork my own project so you'll need to save this as a patch apply this yourself using `git apply <patch>`. Compiles but not tested :)

```
diff --git a/main.go b/main.go
index 4a9d26f..d27c585 100644
--- a/main.go
+++ b/main.go
@@ -13,9 +13,6 @@ import (
        "os"
 )

-type vaultResponse struct {
-       Data certData `json:"data"`
-}
 type certData struct {
        Certificate string `json:"certificate"`
        PrivateKey  string `json:"privateKey"`
@@ -62,16 +59,16 @@ func main() {
                log.Fatal(err)
        }

-       input := vaultResponse{}
+       input := certData{}
        if err := json.Unmarshal(inputData, &input); err != nil {
                log.Fatal(err)
        }

-       if input.Data.PrivateKey == "" || input.Data.Certificate == "" {
+       if input.PrivateKey == "" || input.Certificate == "" {
                log.Fatal("private key or certificate data cannot be nil")
        }

-       p12, err := convert(input.Data, *password)
+       p12, err := convert(input, *password)
        if err != nil {
                log.Fatal(err)
        }
```

**Comment by Brandon-Muller** [comment]
Works like a charm!  Thank you very much!!

**Pull request closed without merging**
